CREATE TABLE url_mappings
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_code   VARCHAR(10) UNIQUE,
    original_url VARCHAR(255) NOT NULL,
    created_at   TIMESTAMP
);